version: 0.2

phases:
  pre_build:
    commands:
      - echo "Login to Docker Hub"
      - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin

  build:
    commands:
      - docker build -t kirana-docker:latest .
      

  post_build:
    commands:
      - docker tag kirana-docker:latest ${DOCKERHUB_USERNAME}/kirana-docker:latest
      - docker push ${DOCKERHUB_USERNAME}/kirana-docker:latest
